### ISSUE TITLE
Update to Angular 6

### ISSUE THREAD

**Issue by kpfromer** [ryuKKu-/angular-particle#14]
Since [angular 6 was released](https://blog.angular.io/version-6-of-angular-now-available-cc56b0efa7a4), I was wondering if this amazing library would update to use it. I am willing to work on this issue if needed! Here is what needs to be updated according to `ng update`: 
```
package "angular-particle" has an incompatible peer dependency to "rxjs" (requires "^5.1.0", would install "6.1.0").
Package "angular-particle" has an incompatible peer dependency to "@angular/core" (requires ">=5.0.0-rc.0 <6.0.0||>=4.0.0 <5.0.0", would install "6.0.0").
```

**Comment by edwardwilson** [comment]
I have put a PR in which moves angular-particales to Angular 7 (which right now is the latest release) #18
